//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Scrum.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Scrum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstreixSymbol {
            get {
                return ResourceManager.GetString("AstreixSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any blockers? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlockersText {
            get {
                return ResourceManager.GetString("BlockersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I&apos;m not running a scrum right now. Use this command to end an active scrum. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompleteScrumErrorText {
            get {
                return ResourceManager.GetString("CompleteScrumErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   end scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompleteScrumText {
            get {
                return ResourceManager.GetString("CompleteScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompleteScrumTitle {
            get {
                return ResourceManager.GetString("CompleteScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One scrum runs at a time. When you’re done, select End scrum at the bottom of the form. Once you end a scrum, no one can make any more updates to that scrum. Just start a new scrum when you’re ready to get status updates again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CompleteScrumTourText {
            get {
                return ResourceManager.GetString("CompleteScrumTourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Something went wrong. Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Something went wrong and I can’t do that right now. Try again in a few minutes.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I can only be used in group chat with no more than 20 members. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MemberCountErrorMessage {
            get {
                return ResourceManager.GetString("MemberCountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Active Scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoActiveScrumTitle {
            get {
                return ResourceManager.GetString("NoActiveScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} You are not a part of the running scrum. Only active members of the scrum can mark it as completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPartOfCompleteScrumText {
            get {
                return ResourceManager.GetString("NoPartOfCompleteScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} You&apos;re not in the scrum that&apos;s currently running. Once that scrum has ended, you can start a new one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPartOfScrumStartText {
            get {
                return ResourceManager.GetString("NoPartOfScrumStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    You are not a part of the running scrum. You’ll be able to enter your updates next scrum onwards. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPartOfScrumUpdateText {
            get {
                return ResourceManager.GetString("NoPartOfScrumUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} You are not a part of the running scrum. You’ll be able to initiate a new scrum once the active scrum is completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotPartofScrumText {
            get {
                return ResourceManager.GetString("NotPartofScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter info (1000 characters max) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I can only run one scrum at a time. End the current scrum first, then start a new one. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RunningScrumMessage {
            get {
                return ResourceManager.GetString("RunningScrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I am currently designed to work only in Group chats. Please install me in a group chat to start tracking your scrum updates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScopeErrorMessage {
            get {
                return ResourceManager.GetString("ScopeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrum completed by {0}, {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumCompletedByText {
            get {
                return ResourceManager.GetString("ScrumCompletedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nice Work! This scrum is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumCompleteText {
            get {
                return ResourceManager.GetString("ScrumCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I can only support below commands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumHelpMessage {
            get {
                return ResourceManager.GetString("ScrumHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Scrum started by {0}, {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumRequestedByText {
            get {
                return ResourceManager.GetString("ScrumRequestedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumTaskModuleTitle {
            get {
                return ResourceManager.GetString("ScrumTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scrum updated by {0}, {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScrumUpdatedByText {
            get {
                return ResourceManager.GetString("ScrumUpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowScrumDetailsTitle {
            get {
                return ResourceManager.GetString("ShowScrumDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartCarouselCardTitle {
            get {
                return ResourceManager.GetString("StartCarouselCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    
        ///When you ask me to start a scrum, I’ll create a form where people can enter their current status. Everyone can look at these updates.
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartCommandTourTextPart1 {
            get {
                return ResourceManager.GetString("StartCommandTourTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Want to start a scrum now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartCommandTourTextPart2 {
            get {
                return ResourceManager.GetString("StartCommandTourTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start scrum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubmitTitle {
            get {
                return ResourceManager.GetString("SubmitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take a tour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Here’s a tour of what I can do. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TakeTourWelcomeMessage {
            get {
                return ResourceManager.GetString("TakeTourWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What will you do today? *(required)* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TodayText {
            get {
                return ResourceManager.GetString("TodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This field can&apos;t be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TodayValidationText {
            get {
                return ResourceManager.GetString("TodayValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last updated on {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateScrumTimeStampText {
            get {
                return ResourceManager.GetString("UpdateScrumTimeStampText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateScrumTitle {
            get {
                return ResourceManager.GetString("UpdateScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User is not from the expected tenant に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningTextForTenantFailure {
            get {
                return ResourceManager.GetString("WarningTextForTenantFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///I help you get status updates from your team. Everyone in the group chat can participate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WelcomeCardContentPart1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Want to know more? Take a tour! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WelcomeCardContentPart2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What did you do yesterday?*(required)* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesterdayText {
            get {
                return ResourceManager.GetString("YesterdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This field can&apos;t be empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesterdayValidationText {
            get {
                return ResourceManager.GetString("YesterdayValidationText", resourceCulture);
            }
        }
    }
}
